# For more info on HTTP files go to https://aka.ms/vs/httpfile
 @Api_Host =  https://api-rzf6vttdizuz4.azurewebsites.net
#@Api_Host =  https://localhost:7161

POST {{Api_Host}}/api/urls
Accept: application/json
Content-Type: application/json
{
  "longUrl": "http://www.google.com",
  "createdBy": "thiago.prohaska@gmail.com"
}
###
